version: '3.4'

services:
  simplecliniqapi:
    image: ${DOCKER_REGISTRY-}simplecliniqapi
    build:
      context: .
      dockerfile: src/SimpleCliniq.Api/Dockerfile

  SimpleIdentityServer:
    image: quay.io/keycloak/keycloak:latest
    container_name: SimpleIdentity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080
  SimpleRedis:
     image: redis:latest
     container_name: SimpleRedis
     restart: always
     ports:
       - 6379:6379

 