version: '3.4'

services:
  simplecliniqapi:
    image: ${DOCKER_REGISTRY-}simplecliniqapi
    build:
      context: .
      dockerfile: src/SimpleCliniq.Api/Dockerfile
  simple.fe:
     image: chbudi9/simplecliniqfe:latest
     command: >
      sh -c "http-server dist -S -C certificate.pem -K key.pem"
     container_name: simplecliniq.fe
     restart: always
     ports:
       - 8090:8080
