// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MMasterTnd
{
    public long IdGroupTarif { get; set; }

    public string NmgroupTarif { get; set; }

    public string KdTarifDetail { get; set; }

    public string NmTarifDetail { get; set; }

    public string Kelas { get; set; }

    public decimal? Harga { get; set; }

    public decimal? IsAktif { get; set; }

    public decimal? HargaBpjs { get; set; }
}