// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MMorfologi
{
    public int IdMorfologi { get; set; }

    public string KdMorfologi { get; set; }

    public string NmMorfologi { get; set; }

    public string KdDiagnosa { get; set; }

    public int? IdDiagnosa { get; set; }

    public bool? IsAktif { get; set; }

    public virtual MDiagnosa IdDiagnosaNavigation { get; set; }
}