// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleCliniq.Module.Core.Domain.Models;

public partial class MPaketRekanan
{
    public long IdPaketRekanan { get; set; }

    public decimal OldIdPaketRekanan { get; set; }

    public string IdMasterPemeriksaanPenunjang { get; set; }

    public long OldIdMasterPemeriksaanPenunjang { get; set; }

    public string RekananId { get; set; }

    public long OldRekananId { get; set; }

    public bool? IsAktif { get; set; }
}